# Generated by Django 5.1.14 on 2026-04-24 08:22
# Manually edited to add pgvector extension + HNSW cosine index on agent_embedding_chunk

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0081_remove_botevent_valid_event_type_event_sub_type_combinations_and_more'),
    ]

    operations = [
        # Ensure pgvector extension is present
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="-- intentionally left blank (extension may be used by others)",
        ),
        migrations.CreateModel(
            name='EmbeddingChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity_table', models.CharField(max_length=64)),
                ('entity_id', models.UUIDField()),
                ('chunk_index', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
            ],
            options={
                'verbose_name': 'Embedding Chunk',
                'db_table': 'agent_embedding_chunk',
                'indexes': [models.Index(fields=['entity_table', 'entity_id'], name='agent_embed_entity__e65a8b_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity_table', 'entity_id', 'chunk_index'), name='unique_embedding_chunk_per_entity')],
            },
        ),
        migrations.CreateModel(
            name='MeetingSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('rrule', models.CharField(blank=True, default='', max_length=512)),
                ('google_calendar_event_id', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Meeting Series',
                'verbose_name_plural': 'Meeting Series',
                'db_table': 'agent_meeting_series',
                'indexes': [models.Index(fields=['is_active', '-updated_at'], name='agent_meeti_is_acti_59e1d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='MeetingOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('transcript_text', models.TextField(blank=True, default='')),
                ('attendees', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bots.bot', to_field='object_id')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='agent.meetingseries')),
            ],
            options={
                'verbose_name': 'Meeting Occurrence',
                'db_table': 'agent_meeting_occurrence',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('gemini_live', 'Gemini Live'), ('chat', 'Chat'), ('webhook', 'Webhook')], default='gemini_live', max_length=32)),
                ('occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='agent.meetingoccurrence')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='agent.meetingseries')),
            ],
            options={
                'db_table': 'agent_conversation',
            },
        ),
        migrations.CreateModel(
            name='ContextItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='context_items', to='agent.conversation')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='context_items', to='agent.meetingseries')),
            ],
            options={
                'verbose_name': 'Context Item',
                'db_table': 'agent_context_item',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('note', 'Note'), ('link', 'Link'), ('file', 'File'), ('chart', 'Chart'), ('image', 'Image')], default='note', max_length=32)),
                ('content', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('is_deleted', models.BooleanField(default=False)),
                ('occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='agent.meetingoccurrence')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='agent.meetingseries')),
            ],
            options={
                'db_table': 'agent_artifact',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=16)),
                ('content', models.TextField(blank=True, default='')),
                ('tool_name', models.CharField(blank=True, default='', max_length=128)),
                ('tool_input', models.JSONField(blank=True, null=True)),
                ('tool_output', models.JSONField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.conversation')),
            ],
            options={
                'db_table': 'agent_message',
            },
        ),
        migrations.CreateModel(
            name='ProjectIntelligence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('decisions_noted', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('open_questions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agent.meetingoccurrence')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence', to='agent.meetingseries')),
            ],
            options={
                'verbose_name': 'Project Intelligence',
                'verbose_name_plural': 'Project Intelligence',
                'db_table': 'agent_project_intelligence',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'Todo'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=32)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=16)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('position', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='agent.task')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agent.meetingseries')),
            ],
            options={
                'db_table': 'agent_task',
            },
        ),
        migrations.CreateModel(
            name='MeetingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=512)),
                ('assignee', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_tasks', to='agent.meetingoccurrence')),
                ('promoted_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agent.task')),
            ],
            options={
                'verbose_name': 'Meeting Task',
                'db_table': 'agent_meeting_task',
            },
        ),
        migrations.AddIndex(
            model_name='meetingoccurrence',
            index=models.Index(fields=['series', '-started_at'], name='agent_meeti_series__9e7c40_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingoccurrence',
            index=models.Index(fields=['bot'], name='agent_meeti_bot_id_69c697_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='agent_conve_updated_16c791_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['series', 'is_deleted', '-updated_at'], name='agent_artif_series__4549a8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='agent_messa_convers_a1e1dd_idx'),
        ),
        migrations.AddIndex(
            model_name='projectintelligence',
            index=models.Index(fields=['series', '-created_at'], name='agent_proje_series__56d612_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['series', 'status', '-updated_at'], name='agent_task_series__39cb0d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='agent_task_due_dat_662736_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingtask',
            constraint=models.UniqueConstraint(fields=('occurrence', 'title'), name='unique_meeting_task_title_per_occ'),
        ),
        # HNSW index for fast approximate nearest-neighbour cosine search
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS agent_embedding_chunk_hnsw_cosine "
                "ON agent_embedding_chunk USING hnsw (embedding vector_cosine_ops) "
                "WITH (m = 16, ef_construction = 64);"
            ),
            reverse_sql="DROP INDEX IF EXISTS agent_embedding_chunk_hnsw_cosine;",
        ),
    ]
